"""empty message

Revision ID: 71b193002962
Revises: 1675f25dff71
Create Date: 2017-12-05 15:43:27.520994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71b193002962'
down_revision = '1675f25dff71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_column('user', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_id', sa.INTEGER(), nullable=False))
    op.drop_column('user', 'id')
    # ### end Alembic commands ###
